### ISSUE TITLE
Since php 7.2 Object is a reserved word

### ISSUE THREAD

**Issue by milovanderlinden** [monarc-project/zm-core#11]
Cannot use 'Object' as class name as it is reserved in /development/MonarcAppFO/vendor/monarc/core/src/MonarcCore/Model/Entity/Object.php on line 22

See https://secure.php.net/manual/en/reserved.other-reserved-words.php

Of course this is no problem when using an older php version, but in my case (running a dev server on archlinux) the application is broken.

**Comment by cedricbonhomme** [comment]
Thank you for the notification. We plan to work soon on making the application compatible with the last stable version of ZendFramework. We will handle this.

**Comment by milovanderlinden** [comment]
Thank you for the resp

**Comment by cedricbonhomme** [comment]
For your information the next MONARC release (will be published soon) will be PHP 7.2 compatible.
